main: io.papermc.chunky_player_pause.ChunkyPlayerPause
name: Chunky_Player_Pause
version: "1"
api-version: "1.21.10"
author: WarierSign
description: This Plugin pauses/starts the Chunky Plugin, when a/all Player joins/leaves
commands:
  cpp:
    description: Chunky Player Pause
    usage: "For a list of commands, type /cpp help"
    aliases: chunkyplayerpause
permissions:
  chunky_player_pause.*:
    description: Grants all permissions of this plugin
    default: op